apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s-export
spec:
  selector:
    matchLabels:
      app: nestjs-k8s-export
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-k8s-export
    spec:
      containers:
        - name: nestjs-k8s-export
          image: satravasso/nestjs-k8s-export
          ports:
            - containerPort: 5000
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-k8s-export
spec:
  selector:
    app: nestjs-k8s-export
  ports:
    - protocol: TCP
      port: 5000
  type: LoadBalancer